name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env: 
        TARGET1_TOKEN: ${{ secrets.TARGET1_TOKEN }}
        BUILD: ${{ format('{0} {1}', 'Build ', github.run_number) }}
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Check
      id: check
      uses: tesults/tesults-api-results-check@1.0.4
      with:
        target: ${{ secrets.TARGET1_ID }}
        build: ${{ format('{0} {1}', 'Build ', github.run_number) }}
        api_token: ${{ secrets.API_TOKEN }} 
      # Use the output from the `Check` step
    - name: Get the number of passes and total
      run: echo "${{ steps.check.outputs.pass }} pass out of ${{ steps.check.outputs.total }} total"
    #- name: Check
    #  env: 
    #    API_TOKEN: ${{ secrets.API_TOKEN }}
    #    TARGET1_ID: ${{ secrets.TARGET1_ID }}
    #    BUILD: ${{ format('{0} {1}', 'Build ', github.run_number) }}
    #  run: npm run check
      
